- db/createTables-mysql.sql
on Linux MySql table names are case-sensitive
> Feature/slts 12 fix db table watchListUserProfiles

- src/org/scada_lts/dao/DAO.java
- src/org/scada_lts/dao/FlexProjectDAO.java
- src/org/scada_lts/dao/ScheduledEventDAO.java
Rework after review. Change deprecated  method queryForInt to queryForObject.
> SLTS-13 Rework after review. Change deprecated  method queryForInt to queryForObject.

- src/br/org/scadabr/vo/scripting/ContextualizedScriptVO.java
- src/org/scada_lts/dao/ScriptDAO.java
- test/org/scada_lts/dao/ScriptDaoTest.java
- test/org/scada_lts/dao/createTables-mysql.sql
Major changes:
- new ScriptDAO
- test for ScriptDAO
> Slts 13 remove dependencis from sero utils

- ScadaLTS-UI/src/app/appBody/point-hierarchy/point-hierarchy.component.ts
> feat(): #207 Old buttons from view hierarchy removed

- WebContent/WEB-INF/classes/env.properties
- src/com/serotonin/mango/MangoContextListener.java
Fixed crash when this property was unavailable (commented)
> #320 Running in safe mode -Fixing exceptions when property is commented

- src/com/serotonin/mango/web/dwr/DataPointDetailsDwr.java
- src/org/scada_lts/dao/pointvalues/PointValueDAO.java
- src/org/scada_lts/mango/service/PointValueService.java
To solve the problem you need to see the mango code and
written test scenarios which, in the case of point written in the SCADA, are the most complicated part.
I suspect this never worked.
> #347 Correcting save datapoint and render getHistoryTableData

- src/org/scada_lts/serorepl/utils/ArrayUtils.java
- test/org/scada_lts/serorepl/utils/ArrayUtilsTest.java
Added new version of method used in Scada
Added test for new methods
> Added class ArrayUtils to package serorepl, with methods used in Scada

- doc/testAPI/ScadaBR.postman_collection
- src/org/scada_lts/web/mvc/api/ViewAPI.java
localhost replaced to localhost:8080 in Postman collection
> REST name fixed

- ScadaLTS-UI-1/src/components/CMP.vue
> #799 Added the possibility that the action would be performed without

- WebContent/WEB-INF/jsp/dataPointEdit.jsp
- WebContent/WEB-INF/jsp/dataSourceEdit.jsp
- WebContent/WEB-INF/jsp/pointEdit/buttons.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectors.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/alphanumeric_state.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/analog_high_limit.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/analog_low_limit.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/binary_state.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/multistate_state.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/negative_cusum.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/no_change.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/no_update.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/point_change.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/positive_cusum.jsp
- WebContent/WEB-INF/jsp/pointEdit/eventDetectorsTypes/state_change_count.jsp
- WebContent/resources/restApiBusinessObjectForDwrScriptSessionId.js
- src/com/serotonin/mango/Common.java
- src/com/serotonin/mango/ScriptSessionAndUsers.java
- src/com/serotonin/mango/db/dao/DataPointDao.java
- src/com/serotonin/mango/db/dao/DataSourceDao.java
- src/com/serotonin/mango/web/dwr/DataPointEditDwr.java
- src/com/serotonin/mango/web/dwr/MiscDwr.java
- src/com/serotonin/mango/web/mvc/controller/DataPointDetailsController.java
- src/org/scada_lts/mango/adapter/MangoWatchList.java
- src/org/scada_lts/mango/service/DataPointService.java
- src/org/scada_lts/session/HttpSessionListenerImpl.java
- src/org/scada_lts/web/mvc/api/BusinessObjectForScriptSessionIdAPI.java
- src/org/scada_lts/web/mvc/controller/DataPointEditController.java
- src/org/scada_lts/web/mvc/controller/FinalValuesForControllers.java
> Revert "Revert "Feature/#810 rest api unlock business object for dwr script session""

- src/com/serotonin/mango/vo/report/ImageChartUtils.java
(cherry picked from commit b80f332)
> #838 Changed shape of drawing chart for numerical points

- src/br/org/scadabr/rt/scripting/ContextualizedScriptRT.java
According to email conversation, because of Context.enter is deprecat…
> previous Context creation way was deprecated

- src/com/serotonin/mango/web/dwr/UsersDwr.java
Very small fix but how important
> Issue#934 - Return information that user in not unique.

- .travis.yml
Change file .travis.yml section branches:only: set siv/develop and master branches
fix: #1140
> #1140 Improving process build branch master

- .travis.yml
- src/com/serotonin/mango/rt/event/handlers/EmailHandlerRT.java
Added information about eventId.
Added information about alias (title).
Added information about stack trace to log.
Added information about notyfication.
fix: #1142
> #1142 Correcting to more readable exception with problem send email

- src/org/scada_lts/web/mvc/api/components/cmp/model/ReadValuePointDTO.java
Corrected conversion to type MangoValue.
> #1156 Correcting interpretation null for CMP component

- scadalts-ui/src/apps/App.vue
Initiate new version template with sidebar + navbar
> #1168 Added Part of the template (navbar) for the new Alarm Lists

- WebContent/WEB-INF/jsp/app.jsp
- WebContent/WEB-INF/springDispatcher-servlet.xml
- WebContent/WEB-INF/tags/page.tag
Added configuration in springDispatcher-servlet.xml.
Added new file app.jsp for static content for app.js etc.. because app.jsp is - secure ScadyLTS authentication.
Added in page.tag new Alarm List after old.
fix: #1174
> #1174 Added new element in menu for new Alarm List

- WebContent/WEB-INF/jsp/app.jsp
update app.jsp as html with <div id="app> and correctly js and css files.
fix: #1176
> #1176 Added new alarm list as new vue.js

- .travis.yml
- scadalts-ui/package.json
- scadalts-ui/src/apps/App.vue
sidebar improvement
fix: #1180
> #1180 Create sidebar in vuejs app for new alarm list #1180

- scadalts-ui/src/apps/App.vue
> #1188 Create navbar in vuejs app for new alarm list

- scadalts-ui/src/router.js
- scadalts-ui/src/views/Alarms.vue
- scadalts-ui/src/views/components/AlarmsComponent.vue
Added initial version alarmsComponent, added view Alarms, modifying routing About/Alarms (views).
fix: #1190
> #1190 Create alarm list component in vuejs app for new alarm list

- scadalts-ui/src/store/alarms/index.js
- scadalts-ui/src/store/index.js
- scadalts-ui/src/views/Alarms.vue
- scadalts-ui/src/views/components/AlarmsComponent.vue
Added initial version vuex store/alarms/index.js
Get data (fake) from vuex for AlarmComponent
Render data in AlarmsComponent base on data (not finish to change css style).
fix: #1192
> #1192 Create vuex in vuejs app for new alarm list

- scadalts-ui/src/views/components/AlarmsComponent.vue
- scadalts-ui/src/views/components/base/pagination/Pagination.vue
- scadalts-ui/src/views/components/base/pagination/PaginationTrigger.vue
Initial version Pagination
Added component Pagination
Added component PaginationTrigger
Proposition use on the AlarmComponent
fix: #1195
> #1205 Adding paging for the list alarm #1205

- scadalts-ui/package.json
- scadalts-ui/src/views/Alarms.vue
> #1218 Initial version refresh data

- .travis.yml
Added branch 1183 and 1165 to build on the travis.
fix #1271
> #1271 Added branch 1183 to build on the travis

- src/org/scada_lts/dao/migration/mysql/V2_2_1_1__View_ApiAlarmsLive_For_PointValueWarningsAndAlarms.java
sort of result by activationTime
> #1197 Update V2_2_1_1__View_ApiAlarmsLive_For_PointValueWarningsAndAlarms.java

- .travis.yml
latest build docker from release_23
dev build docker from develop
clean old build docker
> #1370 Correcting build process on travis

- scadalts-ui/src/components/watch_list/WatchListJsonChart.vue
> #1364 Compare datapoints name are not disappearing

- .travis.yml
> UPDATE version openjdk to 1.11

- .travis.yml
- Required form migration from Vue.js 2 to version 3
fix #1414
> Update to nodejs version 12 LTS

- WebContent/WEB-INF/jsp/views.jsp
- scadalts-ui/src/components/graphical_views/RefreshView.vue
- scadalts-ui/src/main.js
- scadalts-ui/src/store/graphicView/index.js
- scadalts-ui/src/store/graphicView/storeRefreshViews.js
- src/org/scada_lts/dao/ViewDAO.java
- src/org/scada_lts/web/mvc/api/ViewAPI.java
- when the view is open on many screens, it requires that after changing the definition, the screens are freshened up
fix #1418
> ADD refresh view

- WebContent/WEB-INF/jsp/views.jsp
- correct refreshing view after change definition
#1442
> CORRECTING refresh view

- WebContent/WEB-INF/jsp/mailingLists.jsp
This removed line was avoiding all default bahaviour in the mailingList.jsp for email address input select and every element in the page
> Fix MailingList dropdown button. #1486

- build.gradle
Change from implementation to providedCompile to not duplicate the jar libraries.
> Change build.gradle file #1501

- doc/RESTAPI/ScadaLTS_API_OAS3.yaml
- scadalts-ui/src/store/dataPoint/index.js
- src/org/scada_lts/dao/model/point/PointValueTypeOfREST.java
- src/org/scada_lts/utils/ValidationUtils.java
- src/org/scada_lts/web/mvc/api/PointValueAPI.java
Pass the point value inside request body. Validate that value and proceed.
> Fix SetValue method #1538

- scadalts-ui/src/store/dataPoint/templates.js
- scadalts-ui/src/store/systemSettings/index.js
- scadalts-ui/src/views/DataPointDetails/PointProperties/PointPropEventRenderer.vue
- scadalts-ui/src/views/RecipientList/RecipientListDetails.vue
- src/org/scada_lts/web/mvc/api/SystemSettingsAPI.java
- src/org/scada_lts/web/mvc/api/json/JsonSettingsSmsDomain.java
- Fix SMS Domain component in system settings save method
- Update EventTextRenderer to save type NONE insead of null
- Fix RecipientList hour mismatch.
> Patch and fix version 2.6.0 issues

- WebContent/WEB-INF/tags/displayView.tag
- WebContent/resources/common.css
There was a problem with CSS styles that was changing the background color and panel was not visible.
> 2.6.1 - Fix background color for anonymous views. #1615

- webapp-resources/log4j2.xml
That configuration was provided in classic Log4J #1659
> Change Log4j2 to save logs to CATALINA_BASE instead of CATALINA_HOME.

- WebContent/WEB-INF/jsp/viewEdit.jsp
- src/com/serotonin/mango/view/ResolutionView.java
- src/com/serotonin/mango/view/View.java
- src/org/scada_lts/dao/ViewDAO.java
> Adding new Graphical View resolutions. #1685

- .travis.yml
- scadalts-ui/src/layout/dialogs/CreateEventDetectorDialog.vue
- scadalts-ui/src/locales/de.json
- scadalts-ui/src/locales/en.json
- scadalts-ui/src/store/alarms/notifications.js
- scadalts-ui/src/store/dataPoint/eventDetecotrs.js
- scadalts-ui/src/store/dataPoint/templates.js
- scadalts-ui/src/store/index.js
- scadalts-ui/src/views/DataPointDetails/PointProperties/PointPropEventDetectors.vue
- src/org/scada_lts/web/mvc/api/EventDetectorAPI.java
#1672 Using more generic method for that.
Closes: #1672
> fix UI for Creating Event Detectors from new UI

- WebContent/WEB-INF/jsp/include/compoundEditor.jsp
- WebContent/WEB-INF/jsp/include/settingsEditor.jsp
- WebContent/WEB-INF/jsp/include/staticEditor.jsp
- WebContent/WEB-INF/jsp/viewEdit.jsp
- src/com/serotonin/mango/web/dwr/ViewDwr.java
- webapp-resources/messages_de.properties
- webapp-resources/messages_en.properties
- webapp-resources/messages_es.properties
- webapp-resources/messages_fi.properties
- webapp-resources/messages_fr.properties
- webapp-resources/messages_lu.properties
- webapp-resources/messages_nl.properties
- webapp-resources/messages_pl.properties
- webapp-resources/messages_pt.properties
- webapp-resources/messages_ru.properties
- webapp-resources/messages_zh.properties
Add input for X and Y coordinates for most common graphical view components.
> #1769 ADD X and Y component position settings.

- scadalts-ui/src/components/amcharts/RangeChartComponent.vue
- scadalts-ui/src/components/watch_list/WatchListJsonChart.vue
- scadalts-ui/src/components/watch_list/components/ChartSettingsCompareComponent.vue
- scadalts-ui/src/components/watch_list/components/ChartSettingsStaticComponent.vue
- scadalts-ui/src/locales/de.json
- scadalts-ui/src/locales/en.json
Additionaly the styles in Modern WatchList has been fixed. 
close: #1785
> #1758 FIX Time-input for RangeChart

- scadalts-ui/src/components/amcharts/AmChart.js
- scadalts-ui/src/views/DataPointDetails/index.vue
Fixed:
- Data Point Details Chart component is rendering
- Binary Axis shows only values from [0,1] with small padding.
> #1792 FIX DataPoint Details chart

- scadalts-ui/src/store/systemSettings/index.js
- scadalts-ui/src/views/SystemSettings/DataBaseInfoComponent.vue
- scadalts-ui/src/views/SystemSettings/index.vue
Database section has been migrated to separate file to not disturb the main SystemSettings component behaviour.
There are Skeleton Loaders that inform user that the data is loading for slow connection and long responses.
> #1836 ADD Skeleton Loader for Database section.

- .github/workflows/build.yml
- .github/workflows/master.yml
Tomcat 9.0.52 is no more available so moved to next one version 9.0.53.
> Upgrade tomcat9 to newer version

- src/com/serotonin/mango/vo/User.java
Added annotation instead of deleting method
> Bugfix2/#1895 Error with disabled user on Recipient list on newUI

- scadalts-ui/src/components/graphical_views/watchdog/README.md
- scadalts-ui/src/components/graphical_views/watchdog/index.vue
- scadalts-ui/src/main.js
- scadalts-ui/tests/unit/WatchDogComponent/IsAlive2.spec.js
> Change IsAlive2 parameter name

- scadalts-ui/src/layout/NavigationBar.vue
> #2243 Disabled Graphical View 2.0
